services:
  fvttapi:
    container_name: fvttapi
    image: fvttapidev
    ports:
      - "3000:3000"
      - "9222:9222"
#    command: ['sleep', '300']
#    volumes:
#      - /data/swdev:/data
    environment:
      MONGO_HOST: 10.0.0.25
      MONGO_DB: fvttapidev
      MONGO_USER: fvttapidev
      MONGO_PASS: 'fvttapidev'
      AUTH_STRATEGY: 'discord'
      DISCORD_GUILD_ID: '342165983642910720'
      DISCORD_ROLE_ID: '380468763985838081'
      DISCORD_GM_ROLE_ID: '380468748815040516'
      DISCORD_CLIENT_ID: '713381169349263361'
      DISCORD_CLIENT_SECRET: 'OyknwjsoL86TO2-ZjLtMNFKMx8gdmFoK'
      SECRET_KEY: '71bca9b30ca9b28e068fd749cd40050c316056aabc38dba65396c9c0e66d450a'
      FOUNDRY_HOST: 'https://dev.cclloyd.com/v12'
      FOUNDRY_USER: 'dqAHANgKXUkd2Kfi'
      FOUNDRY_PASS: 'Slipspace'
      FOUNDRY_LOG_ENABLED: 'false'
      # FOUNDRY_ADMIN_PASS: 'CHANGEME'  # Optional.  Gives additional control over restarting and managing the game.

#  mongo:
#    container_name: mongo
#    image: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: 'shittywizard'
#      MONGO_INITDB_ROOT_PASSWORD: 'CHANGEME'

#  redis:
#    container_name: redis
#    image: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data
#    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongo-data:
  redis-data: