services:
  fvttapi:
    container_name: fvttapi
    image: fvttapi
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY: 'CHANGEME'
      # MONGO_HOST: 'localhost'
      # MONGO_PASS: '27017'
      # MONGO_DB: 'fvttapi'
      MONGO_USER: 'fvttapi'
      MONGO_PASS: 'CHANGEME'

      # Foundry settings
      FOUNDRY_HOST: 'https://dnd.example.com'
      FOUNDRY_USER: 'APIUser'
      FOUNDRY_PASS: 'CHANGEME'
      # FOUNDRY_ADMIN_PASS: '' # Optional.  Gives additional control over restarting and managing the game.
      # FOUNDRY_LOG_ENABLED: 'false'

      # AUTH_STRATEGY: 'discord' # discord, oidc, disabled

      # Discord auth settings
      DISCORD_CLIENT_ID: 'CHANGEME'
      DISCORD_CLIENT_SECRET: 'CHANGEME'
      # DISCORD_GUILD_ID: ''
      # DISCORD_ROLE_ID: ''
      # DISCORD_GM_ROLE_ID: '' # (if omitted, all users will be considered GMs
      # DISCORD_ADMIN_ROLE_ID: 'ADMIN_ROLE_ID (if omitted, all users will be considered admins in the API, bypassing all permission restrictions.)'

      # OIDC Auth settings
      # OIDC_CLIENT_ID: ''
      # OIDC_CLIENT_SECRET: ''
      # OIDC_EXTRA_SCOPES: ''
      # OIDC_USERNAME_ATTRIBUTE: ''
      # OIDC_ROLE_CLAIM: ''
      # OIDC_GM_ROLE: ''
      # OIDC_ADMIN_ROLE: ''

#  mongo:
#    container_name: mongo
#    image: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: 'fvttapi'
#      MONGO_INITDB_ROOT_PASSWORD: 'CHANGEME'

#volumes:
#  mongo-data:
