# TODO: not triggering on gitea mirror, only on direct push
name: Build and Push Docker Image

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build --push \
            --build-arg UPSTREAM_REPO=https://github.com/${GITHUB_REPOSITORY}.git \
            --build-arg APP_VERSION=${GITHUB_REF_NAME} \
            --tag ${GITHUB_REPOSITORY}:${GITHUB_SHA} \
            --tag ${GITHUB_REPOSITORY}:${GITHUB_REF_NAME} \
            --tag ${GITHUB_REPOSITORY}:latest \
            --file Dockerfile .
